version: '3.7'

services:
  nginx:
    container_name: nns.nginx
    image: nginx:1.19.6-alpine
    volumes:
      - ./src:/var/www/src
      - ./docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
    networks:
      - nns_network

  php:
    container_name: nns.php
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ${PROJECT_VOLUME}:/var/www/src
    user: ${UID}
    networks:
      - nns_network

  postgres:
    container_name: nns.postgres
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - nns_network


volumes:
  pg_volume:
    external: true

networks:
  nns_network:
    driver: bridge